spring.application.name=product-catalog
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/brewedawakening
spring.datasource.username=isaimartinez
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.data.rest.basePath=/api
aws.accessKeyId=${{ secrets.AWS_ACCESS_KEY_ID }}
aws.secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws.s3.bucket-name=${{ secrets.AWS_S3_BUCKET_NAME }}
